---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

# Name und Beschreibung deiner Distro / deines Images
name: HonksOS
description: This is Sir Honks' optimized gaming OS based on Bazzite.

# Wir erben alles von Bazzite, inkl. Gaming-Features
base-image: ghcr.io/ublue-os/bazzite-main
image-version: latest

modules:

  ###########################################################################
  # 1. BRANDING: Deine Dateien (Logo, Wallpaper, Themes) ins System kopieren
  ###########################################################################
  - type: files
    files:
      - source: system
        destination: /
    #
    # Lege deine Dateien so in deinem Repo ab:
    #
    # system/usr/share/backgrounds/honksos-wallpaper.png
    # system/usr/share/pixmaps/honksos-logo.png
    # system/etc/dconf/db/local.d/00-honksos-settings
    #
    # → wird automatisch in / installiert.

  ###########################################################################
  # 2. RPM Layering – zusätzliche Programme
  ###########################################################################
  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro            # CLI Editor
        - starship         # Shell Prompt
        - veracrypt        # Verschlüsselungstool
        - fastfetch        # Sysinfo Tool
        - btop             # Systemmonitor
        # LibreOffice Suite
        - libreoffice-core
        - libreoffice-writer
        - libreoffice-calc
        - libreoffice-impress

    remove:
      packages:
        - firefox
        - firefox-langpacks

  ###########################################################################
  # 3. FLATPAKs – Desktop-Apps, Systemweit installiert
  ###########################################################################
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          # Browser
          - org.mozilla.firefox

          # Gaming
          - com.valvesoftware.Steam
          - net.lutris.Lutris
          - net.davidotek.pupgui2        # ProtonUp-Qt
          - com.usebottles.bottles       # Bottles (Wine Manager)

          # Deine Apps
          - com.github.unrud.PDFarranger
          - com.microsoft.Teams
          - com.github.IsmaelMartinez.zapzap
          - org.localsend.localsend_app
          - it.mijorus.gearlever          # PaperClip
          - org.thunderbird.Thunderbird   # ThunderMail -> Thunderbird

          # Extras / Tools
          - org.gnome.Loupe

      - scope: user

  ###########################################################################
  # 4. Signierung – für sichere OSTree-Images
  ###########################################################################
  - type: signing
