---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

# Name und Beschreibung deiner Distro / deines Images
name: HonksOS
description: This is Sir Honks' optimized gaming OS based on Bazzite.

# Basis-Image: Bazzite mit allen Gaming-Features
base-image: ghcr.io/ublue-os/bazzite-main
image-version: latest

modules:

  ###########################################################################
  # 1. BRANDING: Dateien ins System kopieren (Logo, Wallpaper, Themes)
  ###########################################################################
  - type: files
    files:
      - source: system/usr/share/backgrounds/
        destination: /usr/share/backgrounds/
      - source: system/usr/share/pixmaps/
        destination: /usr/share/pixmaps/
      - source: system/etc/dconf/db/local.d/
        destination: /etc/dconf/db/local.d/
      - source: system/usr/share/plymouth/themes/honksos/
        destination: /usr/share/plymouth/themes/honksos/

  ###########################################################################
  # 2. DNF Layering – zusätzliche RPM Pakete
  ###########################################################################
  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro            # CLI Editor
        - starship         # Shell Prompt
        - veracrypt        # Verschlüsselungstool
        - fastfetch        # Systeminfo
        - btop             # Systemmonitor
        # LibreOffice Suite
        - libreoffice-core
        - libreoffice-writer
        - libreoffice-calc
        - libreoffice-impress
        # Gaming-spezifische Tools (falls nicht bereits in Bazzite enthalten)
        - gamescope
        - mangohud
        - vkBasalt
        - wine
        - wine-32bit-libs
        - protonup-qt

    remove:
      packages:
        - firefox
        - firefox-langpacks

  ###########################################################################
  # 3. Flatpaks – Desktop-Apps, systemweit installiert
  ###########################################################################
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          # Browser
          - org.mozilla.firefox
          # Gaming
          - com.valvesoftware.Steam
          - net.lutris.Lutris
          - net.davidotek.pupgui2        # ProtonUp-Qt
          - com.usebottles.bottles       # Bottles (Wine Manager)
          # Utilities & Productivity
          - com.github.unrud.PDFarranger
          - com.github.IsmaelMartinez.zapzap
          - org.localsend.localsend_app
          - it.mijorus.gearlever          # PaperClip
          - org.thunderbird.Thunderbird   # ThunderMail
          # Extras
          - org.gnome.Loupe

      - scope: user
        install: []  # optional: leere User-Flatpaks, nur Flathub-Repo hinzufügen

  ###########################################################################
  # 4. Signierung – für sichere OSTree-Images
  ###########################################################################
  - type: signing

  ###########################################################################
  # 5. Post-Script – Plymouth Boot-Logo aktivieren
  ###########################################################################
  - type: scripts
    post:
      - /usr/sbin/plymouth-set-default-theme -R honksos
